spring.application.name=OASystem

spring.thymeleaf.encoding=UTF-8
spring.datasource.url=jdbc:mysql://localhost:3306/oa_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Tokyo
spring.datasource.username=root
spring.datasource.password=Wccqwer970809.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

